---
- name: Change local user password
  hosts: windows
  gather_facts: yes
  vars_files:
    - ~/.ansible_vars.yml


  tasks:
  - name: Change the password of a user
    when: ansible_connection == 'winrm'
    ansible.windows.win_user:
      name:    # Replace with the username
      password:  # Replace with the new password
      state: present
