ansible_port: 22192
ansible_user: support
ansible_ssh_pass: 123456a@


local_users:
  - name: waleed
    sudo: true
    nopasswd: true
    password: "123456a@"
  - name: mutaz
    sudo: true
    nopasswd: false
    password: "123456a@"
  - name: support
    sudo: true
    nopasswd: true
    password: "12345a@"

sudo_groups:
  - name: linux-admins@dc.processor.net
    nopasswd: true

login_group_allowed:
  - waleed
  - mutaz
  - root
  - support
  - linux-access@dc.processor.net

#log_server:
#  address: 172.23.70.56
#  port: 1514

#domain_settings:
#  name: DC.PROCESSOR.NET
#  nameservers:
#    - 172.23.70.11
#    - 172.23.70.12
#  join_name: monitor-2@DC.PROCESSOR.NET
#  home_path: /home/processor
#  ad_server:  domain-1-3.dc.processor.net
#  ad_backup_server: domain-2-3.dc.processor.net

#domain_join_password: CWGB7^aXqmX@pBaU5zoK44
